name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Check out code
        uses: actions/checkout@v3.0.0
      - name: Test
        run: |
          make test build
